name: Multi-Module Maven Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Upload all Surefire test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: '**/target/surefire-reports/'

    - name: Display failed test logs from all modules
      if: failure()
      run: |
        echo "🔍 Showing failed test logs from all surefire-reports..."
        find . -type f -path "*/target/surefire-reports/*.txt" | while read file; do
          echo "::group::${file}"
          cat "$file"
          echo "::endgroup::"
        done
